(()=>{
'use strict';
const $=s=>document.querySelector(s);
const c=$('#c'),x=c.getContext('2d'),title=$('#title'),game=$('#game'),toast=$('#toast');
const DT=1/120,MAX_FRAME=.05,MAX_STEPS=8;
const S={run:0,pause:0,last:0,acc:0,w:1,h:1,dpr:1,score:[0,0],win:5,shake:0,flash:0,delay:0,hitstop:0,parts:[],trail:[]};
let cfg={bgm:true,sfx:true,points:5};
try{cfg={...cfg,...JSON.parse(localStorage.getItem('puniSettings')||'{}')}}catch{}
const P=[0,1].map(i=>({i,x:0,y:0,tx:0,ty:0,vx:0,vy:0,ivx:0,ivy:0,t:0,pid:null,r:44,m:2.8,j:0,jv:0,face:0,g:0,sp:0,contact:false,gaugeCd:0,color:i?'#ff6fae':'#4cc9ff',dark:i?'#d73778':'#168ed6'}));
const K={x:0,y:0,vx:0,vy:0,r:20,m:1,spin:0,boost:0};
const keys=new Set();
class GameAudio{
constructor(){this.ctx=null;this.out=null;this.bgm=null;this.ready=false;this.fallback=null;this.hitT=0;this.wallT=0;this.musicStep=0}
unlock(){const AC=window.AudioContext||window.webkitAudioContext;if(!this.ctx&&AC){this.ctx=new AC();this.out=this.ctx.createGain();this.out.gain.value=.34;this.out.connect(this.ctx.destination)}if(this.ctx?.state==='suspended')this.ctx.resume().catch(()=>{});if(cfg.bgm)this.start()}
tone(f,d=.05,v=.05,type='sine',delay=0){if(!cfg.sfx||!this.ctx||!this.out)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime+delay;o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(this.out);o.start(t);o.stop(t+d)}
musicTone(f,d=.13,v=.022,type='triangle'){if(!cfg.bgm||!this.ctx||!this.out)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(this.out);o.start(t);o.stop(t+d)}
start(){if(!cfg.bgm)return;if(!this.bgm){const a=new window.Audio('./assets/audio/bgm/mahou-no-cooking.mp3');a.loop=true;a.preload='auto';a.volume=.28;a.addEventListener('canplay',()=>{this.ready=true;this.stopFallback();if(cfg.bgm)a.play().catch(()=>this.startFallback())});a.addEventListener('error',()=>{this.ready=false;this.startFallback()});this.bgm=a}if(this.ctx?.state==='suspended')this.ctx.resume().catch(()=>{});if(this.ready)this.bgm.play().catch(()=>this.startFallback());else{try{this.bgm.load()}catch{}setTimeout(()=>{if(!this.ready&&cfg.bgm)this.startFallback()},700)}}
stop(){this.bgm?.pause();this.stopFallback()}
resume(){if(this.ctx?.state==='suspended')this.ctx.resume().catch(()=>{});if(cfg.bgm){if(this.ready)this.bgm?.play().catch(()=>this.startFallback());else this.startFallback()}}
startFallback(){if(this.fallback||!this.ctx||!cfg.bgm)return;const melody=[262,330,392,523,392,330,294,349,440,587,440,349],bass=[131,131,147,147,165,165,147,147];this.fallback=setInterval(()=>{if(!cfg.bgm)return;const n=this.musicStep++;this.musicTone(melody[n%melody.length],.14,.025,'triangle');if(n%2===0)this.musicTone(bass[(n>>1)%bass.length],.18,.016,'sine')},165)}
stopFallback(){clearInterval(this.fallback);this.fallback=null}
duck(a=.4,ms=350){if(!this.bgm||!this.ready)return;this.bgm.volume=.28*(1-a);setTimeout(()=>{if(this.bgm)this.bgm.volume=.28},ms)}
hit(kind,p=1){let t=performance.now();if(t-this.hitT<22)return;this.hitT=t;if(kind==='smash'){this.tone(95,.08,.14);this.tone(280,.05,.07,'triangle');this.duck(.2,220)}else if(kind==='graze')this.tone(560,.03,.03,'triangle');else this.tone(160+p*25,.04,.06,'triangle')}
wall(p=1){let t=performance.now();if(t-this.wallT<30)return;this.wallT=t;this.tone(120+p*18,.035,.035,'triangle')}
goal(){this.duck(.5,550);[523,659,784,1046].forEach((f,i)=>this.tone(f,.15,.1,'triangle',i*.05))}
special(){this.duck(.35,420);[330,440,660,880].forEach((f,i)=>this.tone(f,.11,.07,'triangle',i*.04))}
}
const A=new GameAudio();
function save(){try{localStorage.setItem('puniSettings',JSON.stringify(cfg))}catch{}syncUI()}
function syncUI(){[['#bgmToggle','bgm'],['#sfxToggle','sfx']].forEach(([id,k])=>{const e=$(id);if(e){e.classList.toggle('on',cfg[k]);e.textContent=cfg[k]?'ON':'OFF'}});if($('#pointsSelect'))$('#pointsSelect').value=String(cfg.points);S.win=+cfg.points||5;specialUI()}
function rr(p){return p.r*(p.sp?1.34:1)}function pm(p){return p.m*(p.sp?1.7:1)}
function specialUI(){P.forEach((p,i)=>{const f=$('#specialFill'+(i+1)),b=$('#specialBtn'+(i+1)),t=$('#specialText'+(i+1));if(f)f.style.transform=`scaleX(${p.g/100})`;if(t)t.textContent=p.sp?`BURST ${p.sp.toFixed(1)}s`:p.g>=100?'READY!':`${p.g|0}%`;if(b){const ready=p.g>=100&&!p.sp&&S.run&&!S.pause;b.disabled=!ready;b.classList.toggle('ready',ready);b.classList.toggle('active-special',!!p.sp)}})}
function gauge(p,v){if(!p.sp)p.g=Math.min(100,p.g+v)}
function burst(i){const p=P[i];if(!S.run||S.pause||p.sp||p.g<100)return;p.g=0;p.sp=4.5;p.face=.35;p.jv+=(i?1:-1)*2.5;A.special();S.shake=.4;S.flash=.18;particles(p.x,p.y,p.color,30);say((i?'PINK 奥':'手前 BLUE')+' PUNI BURST!');specialUI()}
function resize(){const vv=window.visualViewport;S.dpr=Math.min(2,devicePixelRatio||1);S.w=Math.max(1,Math.round(vv?.width||innerWidth));S.h=Math.max(1,Math.round(vv?.height||innerHeight));c.width=Math.round(S.w*S.dpr);c.height=Math.round(S.h*S.dpr);c.style.width=S.w+'px';c.style.height=S.h+'px';x.setTransform(S.dpr,0,0,S.dpr,0,0);const q=Math.min(S.w,S.h);P.forEach(p=>p.r=Math.min(62,Math.max(32,q*.085)));K.r=Math.max(14,q*.034);P.forEach(clamp);if(!S.run)reset()}
function reset(full=false){P[0].x=S.w*.5;P[0].y=S.h*.78;P[1].x=S.w*.5;P[1].y=S.h*.22;P.forEach(p=>{p.tx=p.x;p.ty=p.y;p.vx=p.vy=p.ivx=p.ivy=0;p.pid=null;p.j=p.jv=0;p.face=0;p.sp=0;p.contact=false;p.gaugeCd=0;if(full)p.g=0});K.x=S.w/2;K.y=S.h/2;K.vx=(Math.random()-.5)*160;K.vy=(Math.random()>.5?1:-1)*200;K.spin=0;K.boost=0;S.acc=0;S.hitstop=0;specialUI()}
function clamp(p){const r=rr(p),pad=r+9,mid=S.h/2,g=-2,minY=p.i?pad:mid+g+r,maxY=p.i?mid-g-r:S.h-pad;p.x=Math.max(pad,Math.min(S.w-pad,p.x));p.y=Math.max(minY,Math.min(maxY,p.y));p.tx=Math.max(pad,Math.min(S.w-pad,p.tx));p.ty=Math.max(minY,Math.min(maxY,p.ty))}
function start(){A.unlock();S.score=[0,0];$('#s1').textContent=$('#s2').textContent='0';title.classList.remove('active');game.classList.add('active');S.run=1;S.pause=0;resize();reset(true);say('READY!');S.last=performance.now();requestAnimationFrame(loop)}
function restart(){S.score=[0,0];$('#s1').textContent=$('#s2').textContent='0';S.pause=0;document.querySelectorAll('.overlay').forEach(o=>o.classList.remove('show'));reset(true);say('READY!')}
function home(){S.run=0;S.pause=0;game.classList.remove('active');title.classList.add('active');document.querySelectorAll('.overlay').forEach(o=>o.classList.remove('show'))}
function say(t){toast.textContent=t;toast.classList.remove('pop');void toast.offsetWidth;toast.classList.add('pop')}
function particles(px,py,col,n=10){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=70+Math.random()*340;S.parts.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:.3+Math.random()*.45,z:3+Math.random()*6,c:col})}if(S.parts.length>160)S.parts.splice(0,S.parts.length-160)}
function pd(e){if(!S.run||S.pause)return;e.preventDefault();const i=e.clientY>=S.h/2?0:1,p=P[i];if(p.pid!==null)return;p.pid=e.pointerId;p.tx=e.clientX;p.ty=e.clientY;p.ivx=p.ivy=0;p.t=e.timeStamp||performance.now();try{c.setPointerCapture(e.pointerId)}catch{}}
function pmove(e){const p=P.find(q=>q.pid===e.pointerId);if(!p||S.pause)return;e.preventDefault();const t=e.timeStamp||performance.now(),d=Math.max(.004,Math.min(.05,(t-p.t)/1000||.016)),vx=(e.clientX-p.tx)/d,vy=(e.clientY-p.ty)/d,m=Math.hypot(vx,vy),sc=m>3300?3300/m:1;p.ivx=vx*sc;p.ivy=vy*sc;p.tx=e.clientX;p.ty=e.clientY;p.t=t;clamp(p)}
function pu(e){const p=P.find(q=>q.pid===e.pointerId);if(!p)return;p.pid=null;p.ivx=p.ivy=0;try{if(c.hasPointerCapture?.(e.pointerId))c.releasePointerCapture(e.pointerId)}catch{}}
c.addEventListener('pointerdown',pd,{passive:false});c.addEventListener('pointermove',pmove,{passive:false});['pointerup','pointercancel','lostpointercapture'].forEach(n=>c.addEventListener(n,pu));
function keyboard(d){const map=[['KeyA','KeyD','KeyW','KeyS'],['ArrowLeft','ArrowRight','ArrowUp','ArrowDown']],spd=Math.max(480,Math.min(1050,Math.min(S.w,S.h)*1.3));P.forEach((p,i)=>{if(p.pid!==null)return;const [l,r,u,dn]=map[i];let dx=(keys.has(r)?1:0)-(keys.has(l)?1:0),dy=(keys.has(dn)?1:0)-(keys.has(u)?1:0);p.ivx=p.ivy=0;if(dx||dy){const m=Math.hypot(dx,dy);p.ivx=dx/m*spd;p.ivy=dy/m*spd;p.tx+=p.ivx*d;p.ty+=p.ivy*d;clamp(p)}})}
function moveP(p,d){const k=430,vf=31,drag=7;p.vx+=((p.tx-p.x)*k+(p.ivx-p.vx)*vf-p.vx*drag)*d;p.vy+=((p.ty-p.y)*k+(p.ivy-p.vy)*vf-p.vy*drag)*d;const lim=p.sp?3000:2700,m=Math.hypot(p.vx,p.vy);if(m>lim){p.vx*=lim/m;p.vy*=lim/m}p.x+=p.vx*d;p.y+=p.vy*d;if(p.pid!==null){const z=Math.exp(-d*17);p.ivx*=z;p.ivy*=z}if(p.sp)p.sp=Math.max(0,p.sp-d);p.gaugeCd=Math.max(0,p.gaugeCd-d);p.jv+=(-90*p.j-14*p.jv)*d;p.j+=p.jv*d;p.j=Math.max(-.32,Math.min(.32,p.j));p.face=Math.max(0,p.face-d);clamp(p)}
function hit(p){const dx=K.x-p.x,dy=K.y-p.y,dist=Math.hypot(dx,dy),min=rr(p)+K.r;if(!dist||dist>=min){p.contact=false;return}const wasContact=p.contact;p.contact=true;const nx=dx/dist,ny=dy/dist,pen=min-dist,invP=1/pm(p),invK=1/K.m,sum=invP+invK;K.x+=nx*pen*invK/sum;K.y+=ny*pen*invK/sum;const rvx=K.vx-p.vx,rvy=K.vy-p.vy,vn=rvx*nx+rvy*ny;if(vn>=0)return;const tx=-ny,ty=nx,vt=rvx*tx+rvy*ty,ns=-vn,ms=Math.hypot(p.vx,p.vy),sm=ns>850||ms>1425,gr=!sm&&Math.abs(vt)>ns*1.25&&ns<500,re=p.sp?1.02:sm?.95:gr?.84:.92;let j=-(1+re)*vn/sum;j=Math.min(j,p.sp?6100:sm?4700:4000);K.vx+=j*invK*nx;K.vy+=j*invK*ny;const fr=gr?.16:.08,jt=Math.max(-j*fr,Math.min(j*fr,-vt/sum));K.vx+=jt*invK*tx;K.vy+=jt*invK*ty;K.spin+=jt*.006;if(p.sp){K.vx+=nx*130;K.vy+=ny*130}const imp=Math.min(5,ns/520),newStrike=!wasContact&&p.gaugeCd<=0&&ns>70;if(newStrike){gauge(p,(sm?15:gr?6:9)+imp*2.4);p.gaugeCd=sm?.24:.18}p.jv-=ny*(.8+imp*.5);p.face=.16;A.hit(sm?'smash':gr?'graze':'normal',imp);particles(K.x,K.y,sm?'#fff1a3':p.color,sm?18:gr?4:7);if(sm){K.boost=Math.max(K.boost,.18);S.hitstop=Math.max(S.hitstop,p.sp?.045:.032);S.shake=Math.max(S.shake,.5);S.flash=Math.max(S.flash,.2)}}
function mallets(){const a=P[0],b=P[1],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=rr(a)+rr(b);if(!d||d>=min)return;const nx=dx/d,ny=dy/d,pen=min-d;a.x-=nx*pen*.5;a.y-=ny*pen*.5;b.x+=nx*pen*.5;b.y+=ny*pen*.5;clamp(a);clamp(b);const vn=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(vn>=0)return;const j=-(1+.55)*vn/(1/pm(a)+1/pm(b));a.vx-=j/pm(a)*nx*.55;a.vy-=j/pm(a)*ny*.55;b.vx+=j/pm(b)*nx*.55;b.vy+=j/pm(b)*ny*.55;particles((a.x+b.x)/2,(a.y+b.y)/2,'#fff',5)}
function bounce(axis,pos){const sp=Math.hypot(K.vx,K.vy),n=Math.abs(axis==='x'?K.vx:K.vy),t=Math.abs(axis==='x'?K.vy:K.vx),b=t>n*1.8?.975:.95;if(axis==='x')K.vx=(pos?1:-1)*Math.abs(K.vx)*b;else K.vy=(pos?1:-1)*Math.abs(K.vy)*b;K.spin*=.9;A.wall(Math.min(4,sp/650));if(sp>950)particles(K.x,K.y,'#ffe8a6',4)}
function currentPuckCap(){if(P.some(p=>p.sp>0))return 1800;if(K.boost>0)return 1600;return 1400}
function physics(d){P.forEach(p=>moveP(p,d));mallets();K.x+=K.vx*d;K.y+=K.vy*d;const gw=Math.min(S.w*.38,240),gx=(S.w-gw)/2;if(K.x-K.r<0){K.x=K.r;bounce('x',1)}if(K.x+K.r>S.w){K.x=S.w-K.r;bounce('x',0)}const goal=K.x>gx&&K.x<gx+gw;if(K.y-K.r<0){if(goal)return score(0);K.y=K.r;bounce('y',1)}if(K.y+K.r>S.h){if(goal)return score(1);K.y=S.h-K.r;bounce('y',0)}P.forEach(hit);const dr=Math.pow(.9987,d*120);K.vx*=dr;K.vy*=dr;K.spin*=Math.pow(.996,d*120);K.boost=Math.max(0,K.boost-d);const sp=Math.hypot(K.vx,K.vy),cap=currentPuckCap();if(sp>cap){K.vx*=cap/sp;K.vy*=cap/sp}}
function score(w){if(S.delay)return;S.score[w]++;gauge(P[w],8);gauge(P[1-w],18);$('#s1').textContent=S.score[0];$('#s2').textContent=S.score[1];A.goal();S.shake=1;S.flash=1;P.forEach(p=>{p.contact=false;p.gaugeCd=.2});particles(K.x,w?S.h-18:18,w?'#ff6fae':'#4cc9ff',36);say('GOAL!');if(S.score[w]>=S.win){S.pause=1;setTimeout(()=>{$('#resultTitle').textContent=(w?'PINK（奥）':'BLUE（手前）')+' WIN!';$('#resultScore').textContent=S.score[0]+' - '+S.score[1];$('#resultOverlay').classList.add('show')},500)}else{S.delay=.7;setTimeout(()=>{if(S.run&&!S.pause){reset();S.delay=0}},720)}}
function updateEffects(d){specialUI();S.trail.push({x:K.x,y:K.y,l:.15});if(S.trail.length>15)S.trail.shift();S.trail.forEach(t=>t.l-=d);S.trail=S.trail.filter(t=>t.l>0);S.parts.forEach(p=>{p.x+=p.vx*d;p.y+=p.vy*d;p.vy+=160*d;p.l-=d});S.parts=S.parts.filter(p=>p.l>0);S.shake=Math.max(0,S.shake-d*18);S.flash=Math.max(0,S.flash-d*3)}
function update(d){if(S.delay){S.delay=Math.max(0,S.delay-d);updateEffects(d);return}keyboard(d);if(S.hitstop>0){S.hitstop=Math.max(0,S.hitstop-d);S.acc=0;updateEffects(d);return}S.acc=Math.min(MAX_FRAME,S.acc+d);let steps=0;while(S.acc>=DT&&steps<MAX_STEPS){physics(DT);S.acc-=DT;steps++;if(S.hitstop>0){S.acc=0;break}}updateEffects(d)}
function field(){const w=S.w,h=S.h,gw=Math.min(w*.38,240),gx=(w-gw)/2,g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,'#4c203d');g.addColorStop(.5,'#20213f');g.addColorStop(1,'#17324e');x.fillStyle=g;x.fillRect(0,0,w,h);x.strokeStyle='rgba(255,255,255,.34)';x.lineWidth=4;x.setLineDash([12,14]);x.beginPath();x.moveTo(0,h/2);x.lineTo(w,h/2);x.stroke();x.setLineDash([]);x.beginPath();x.arc(w/2,h/2,Math.min(72,Math.min(w,h)*.16),0,Math.PI*2);x.stroke();x.lineWidth=9;x.strokeStyle='#ff77b5';x.beginPath();x.moveTo(gx,0);x.lineTo(gx+gw,0);x.stroke();x.strokeStyle='#69d7ff';x.beginPath();x.moveTo(gx,h);x.lineTo(gx+gw,h);x.stroke();x.fillStyle='rgba(0,0,0,.28)';x.fillRect(gx,0,gw,14);x.fillRect(gx,h-14,gw,14)}
function puck(){const g=x.createRadialGradient(K.x-K.r*.35,K.y-K.r*.4,2,K.x,K.y,K.r);g.addColorStop(0,'#fff');g.addColorStop(.18,'#fff4a8');g.addColorStop(.52,'#ffd44d');g.addColorStop(1,'#f38b3e');x.shadowColor='#ffd44daa';x.shadowBlur=18+Math.min(12,Math.hypot(K.vx,K.vy)/120);x.fillStyle=g;x.beginPath();x.arc(K.x,K.y,K.r,0,Math.PI*2);x.fill();x.shadowBlur=0}
function player(p){const r=rr(p),sp=Math.min(1.3,Math.hypot(p.vx,p.vy)/1200),ang=Math.atan2(p.vy,p.vx);x.save();x.translate(p.x,p.y);if(p.sp){x.strokeStyle=p.color;x.globalAlpha=.5;x.lineWidth=5;x.shadowColor=p.color;x.shadowBlur=22;x.beginPath();x.arc(0,0,r*1.14*(1+.05*Math.sin(performance.now()*.012)),0,Math.PI*2);x.stroke();x.globalAlpha=1;x.shadowBlur=0}x.rotate(ang);x.scale(Math.max(.7,1+sp*.11-p.j*.2),Math.max(.7,1-sp*.05+p.j));const g=x.createRadialGradient(-r*.3,-r*.35,r*.08,0,0,r);g.addColorStop(0,'#fff');g.addColorStop(.12,p.sp?'#fff7ba':p.color);g.addColorStop(1,p.dark);x.fillStyle=g;x.beginPath();x.ellipse(0,0,r,r*.93,0,0,Math.PI*2);x.fill();x.restore();x.save();x.translate(p.x,p.y);if(p.i===1)x.rotate(Math.PI);x.fillStyle='#17213a';x.beginPath();x.arc(-r*.22,-r*.1,r*.065,0,Math.PI*2);x.arc(r*.22,-r*.1,r*.065,0,Math.PI*2);x.fill();x.strokeStyle='#17213a';x.lineWidth=Math.max(3,r*.07);x.beginPath();x.arc(0,r*.14,r*.2,.15*Math.PI,.85*Math.PI);x.stroke();x.restore()}
function draw(){x.save();if(S.shake){const m=S.shake*5;x.translate((Math.random()-.5)*m,(Math.random()-.5)*m)}field();S.trail.forEach(t=>{x.globalAlpha=t.l/.15*.24;x.fillStyle='#ffe46b';x.beginPath();x.arc(t.x,t.y,K.r*.7,0,Math.PI*2);x.fill()});x.globalAlpha=1;puck();P.forEach(player);S.parts.forEach(p=>{x.globalAlpha=Math.max(0,p.l/.7);x.fillStyle=p.c;x.beginPath();x.arc(p.x,p.y,p.z,0,Math.PI*2);x.fill()});x.globalAlpha=1;if(S.flash){x.fillStyle=`rgba(255,255,255,${S.flash*.12})`;x.fillRect(0,0,S.w,S.h)}x.restore()}
function loop(n){if(!S.run)return;const d=Math.min(MAX_FRAME,(n-S.last)/1000||1/60);S.last=n;if(!S.pause)update(d);draw();requestAnimationFrame(loop)}
$('#startBtn').onclick=start;$('#howBtn').onclick=()=>$('#howOverlay').classList.add('show');$('#settingsBtn').onclick=()=>$('#settingsOverlay').classList.add('show');document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('.overlay').classList.remove('show'));$('#pauseBtn').onclick=()=>{S.pause=1;$('#pauseOverlay').classList.add('show')};$('#resumeBtn').onclick=()=>{S.pause=0;$('#pauseOverlay').classList.remove('show');S.last=performance.now()};$('#restartBtn').onclick=restart;$('#titleBtn').onclick=home;$('#againBtn').onclick=restart;$('#resultTitleBtn').onclick=home;
function bindBurstButton(id,i){const b=$(id);if(!b)return;b.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();burst(i)},{passive:false});b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation()})}
bindBurstButton('#specialBtn1',0);bindBurstButton('#specialBtn2',1);
$('#bgmToggle').onclick=()=>{cfg.bgm=!cfg.bgm;cfg.bgm?(A.unlock(),A.start()):A.stop();save()};$('#sfxToggle').onclick=()=>{cfg.sfx=!cfg.sfx;save()};$('#pointsSelect').onchange=e=>{cfg.points=+e.target.value||5;save()};
window.addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyP','Escape','KeyQ','Enter'].includes(e.code))e.preventDefault();if(e.code==='KeyQ')return burst(0);if(e.code==='Enter')return burst(1);if(e.code==='KeyP'||e.code==='Escape'){if(S.run&&!S.pause)$('#pauseBtn').click();else if(S.pause&&$('#pauseOverlay').classList.contains('show'))$('#resumeBtn').click();return}keys.add(e.code);A.resume()},{passive:false});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(S.run&&!S.pause){S.pause=1;$('#pauseOverlay').classList.add('show')}});window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden&&S.run&&!S.pause){S.pause=1;$('#pauseOverlay').classList.add('show')}else A.resume()});document.addEventListener('contextmenu',e=>S.run&&e.preventDefault());document.addEventListener('dragstart',e=>e.preventDefault());
if(matchMedia('(pointer:fine)').matches)document.body.classList.add('has-keyboard');syncUI();resize();
})();