(()=>{
'use strict';
const $=s=>document.querySelector(s), canvas=$('#c'), ctx=canvas.getContext('2d');
const title=$('#title'), game=$('#game'), toast=$('#toast');
const FIXED_DT=1/120, MAX_ACC=.05;
const state={running:false,paused:false,last:0,acc:0,w:0,h:0,dpr:1,score:[0,0],goalToWin:5,shake:0,flash:0,particles:[],trails:[],roundDelay:0};
let settings={bgm:true,sfx:true};
try{settings={...settings,...JSON.parse(localStorage.getItem('puniSettings')||'{}')}}catch{}
function saveSettings(){try{localStorage.setItem('puniSettings',JSON.stringify(settings))}catch{}syncToggles()}
function syncToggles(){for(const [id,key] of [['#bgmToggle','bgm'],['#sfxToggle','sfx']]){const el=$(id);el.classList.toggle('on',settings[key]);el.textContent=settings[key]?'ON':'OFF'}}
class AudioManager{
 constructor(){this.ctx=null;this.master=null;this.bgm=null;this.bgmReady=false;this.fallbackTimer=null;this.step=0}
 unlock(){const AC=window.AudioContext||window.webkitAudioContext;if(!this.ctx){if(AC){this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=.34;this.master.connect(this.ctx.destination)}} if(this.ctx?.state==='suspended')this.ctx.resume().catch(()=>{});if(settings.bgm)this.startBgm()}
 resume(){if(this.ctx?.state==='suspended')this.ctx.resume().catch(()=>{});if(this.bgm&&settings.bgm)this.bgm.play().catch(()=>{})}
 tone(f=440,d=.06,type='sine',vol=.08,when=0){if(!settings.sfx||!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime+when;o.type=type;o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+d)}
 hit(speed=1){this.tone(135+Math.random()*70,.05,'sine',Math.min(.13,.045+speed*.023));this.tone(330+Math.random()*120,.035,'triangle',.038)}
 wall(){this.tone(120,.035,'triangle',.032)}
 goal(){[523,659,784,1046].forEach((f,i)=>this.tone(f,.16,'triangle',.11,i*.055))}
 click(){this.tone(520,.035,'sine',.05)}
 makeBgm(){if(this.bgm)return;const a=new Audio('./assets/audio/bgm/shakujii-park.mp3');a.loop=true;a.preload='auto';a.volume=.28;a.addEventListener('canplaythrough',()=>{this.bgmReady=true;this.stopFallback();if(settings.bgm)a.play().catch(()=>{})},{once:true});a.addEventListener('error',()=>{this.bgmReady=false;if(settings.bgm)this.startFallback()});this.bgm=a}
 startBgm(){this.makeBgm();if(this.bgmReady){this.bgm.play().catch(()=>{})}else{this.bgm.load();setTimeout(()=>{if(!this.bgmReady&&settings.bgm)this.startFallback()},900)}}
 stopBgm(){if(this.bgm)this.bgm.pause();this.stopFallback()}
 startFallback(){if(this.fallbackTimer||!this.ctx)return;const seq=[262,330,392,523,392,330,294,349,440,587,440,349];this.fallbackTimer=setInterval(()=>{if(!settings.bgm||!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type='square';o.frequency.value=seq[this.step++%seq.length];g.gain.setValueAtTime(.014,t);g.gain.exponentialRampToValueAtTime(.001,t+.11);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+.12)},165)}
 stopFallback(){clearInterval(this.fallbackTimer);this.fallbackTimer=null}
}
const audio=new AudioManager();
const players=[0,1].map(side=>({side,x:0,y:0,r:46,color:side?'#ff6fae':'#4cc9ff',dark:side?'#d73778':'#168ed6',pid:null,vx:0,vy:0,tx:0,ty:0,mass:2.8,face:0,jx:0,jy:0,jvx:0,jvy:0}));
const puck={x:0,y:0,r:22,vx:0,vy:0,mass:1,max:1650};
const keys=new Set();
const coarse=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
if(matchMedia('(pointer:fine)').matches||!coarse)document.body.classList.add('has-keyboard');
function updateRotateGate(){document.body.classList.toggle('needs-rotate',coarse&&innerHeight>innerWidth)}
function resize(){updateRotateGate();const vv=window.visualViewport;state.dpr=Math.min(2,devicePixelRatio||1);state.w=Math.max(1,Math.round(vv?.width||innerWidth));state.h=Math.max(1,Math.round(vv?.height||innerHeight));canvas.width=Math.round(state.w*state.dpr);canvas.height=Math.round(state.h*state.dpr);canvas.style.width=state.w+'px';canvas.style.height=state.h+'px';ctx.setTransform(state.dpr,0,0,state.dpr,0,0);const r=Math.min(54,Math.max(36,state.h*.095));players.forEach(p=>p.r=r);puck.r=Math.max(16,state.h*.038);players.forEach(clampPlayer);if(!state.running)resetPositions()}
function resetPositions(){players[0].x=state.w*.22;players[0].y=state.h*.5;players[1].x=state.w*.78;players[1].y=state.h*.5;players.forEach(p=>{p.tx=p.x;p.ty=p.y;p.vx=p.vy=0;p.pid=null;p.jx=p.jy=p.jvx=p.jvy=0});puck.x=state.w/2;puck.y=state.h/2;puck.vx=(Math.random()>.5?1:-1)*220;puck.vy=(Math.random()-.5)*180;state.acc=0}
function startMatch(){audio.unlock();state.score=[0,0];$('#s1').textContent=0;$('#s2').textContent=0;title.classList.remove('active');game.classList.add('active');state.running=true;state.paused=false;resize();resetPositions();say('READY!');state.last=performance.now();requestAnimationFrame(loop)}
function endToTitle(){state.running=false;state.paused=false;game.classList.remove('active');title.classList.add('active');document.querySelectorAll('.overlay').forEach(o=>o.classList.remove('show'))}
function restart(){state.score=[0,0];$('#s1').textContent=0;$('#s2').textContent=0;state.paused=false;$('#pauseOverlay').classList.remove('show');$('#resultOverlay').classList.remove('show');resetPositions();say('READY!')}
function say(t){toast.textContent=t;toast.classList.remove('pop');void toast.offsetWidth;toast.classList.add('pop')}
function spawn(x,y,color,n=12){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=80+Math.random()*350;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.45,size:3+Math.random()*7,color})}if(state.particles.length>180)state.particles.splice(0,state.particles.length-180)}
function clampPlayer(p){const pad=p.r+10,mid=state.w/2,gap=12,minX=p.side===0?pad:mid+gap+p.r,maxX=p.side===0?mid-gap-p.r:state.w-pad;if(p.x<minX){p.x=minX;if(p.vx<0)p.vx*=-.2}if(p.x>maxX){p.x=maxX;if(p.vx>0)p.vx*=-.2}if(p.y<pad){p.y=pad;if(p.vy<0)p.vy*=-.2}if(p.y>state.h-pad){p.y=state.h-pad;if(p.vy>0)p.vy*=-.2}}
function pointerDown(e){if(!state.running||state.paused)return;e.preventDefault();const side=e.clientX<state.w/2?0:1,p=players[side];if(p.pid!==null)return;p.pid=e.pointerId;p.tx=e.clientX;p.ty=e.clientY;try{canvas.setPointerCapture(e.pointerId)}catch{}}
function pointerMove(e){if(!state.running||state.paused)return;const p=players.find(q=>q.pid===e.pointerId);if(!p)return;e.preventDefault();p.tx=e.clientX;p.ty=e.clientY}
function pointerEnd(e){const p=players.find(q=>q.pid===e.pointerId);if(!p)return;p.pid=null;try{if(canvas.hasPointerCapture?.(e.pointerId))canvas.releasePointerCapture(e.pointerId)}catch{}}
canvas.addEventListener('pointerdown',pointerDown,{passive:false});canvas.addEventListener('pointermove',pointerMove,{passive:false});['pointerup','pointercancel','lostpointercapture'].forEach(n=>canvas.addEventListener(n,pointerEnd));
function updateKeyboard(dt){const speed=Math.max(360,Math.min(900,state.w*.78)),moves=[['KeyA','KeyD','KeyW','KeyS'],['ArrowLeft','ArrowRight','ArrowUp','ArrowDown']];for(let i=0;i<2;i++){const p=players[i];if(p.pid!==null)continue;const [left,right,up,down]=moves[i];let dx=(keys.has(right)?1:0)-(keys.has(left)?1:0),dy=(keys.has(down)?1:0)-(keys.has(up)?1:0);if(dx||dy){const len=Math.hypot(dx,dy);p.tx+=dx/len*speed*dt;p.ty+=dy/len*speed*dt;const mid=state.w/2,gap=12,pad=p.r+10;p.tx=Math.max(i===0?pad:mid+gap+p.r,Math.min(i===0?mid-gap-p.r:state.w-pad,p.tx));p.ty=Math.max(pad,Math.min(state.h-pad,p.ty))}}}
function stepMallet(p,dt){const k=175,d=24,ax=(p.tx-p.x)*k-p.vx*d,ay=(p.ty-p.y)*k-p.vy*d;p.vx+=ax*dt;p.vy+=ay*dt;const maxV=1500,sp=Math.hypot(p.vx,p.vy);if(sp>maxV){p.vx*=maxV/sp;p.vy*=maxV/sp}p.x+=p.vx*dt;p.y+=p.vy*dt;clampPlayer(p);const sk=235,sd=20;p.jvx+=(-p.jx*sk-p.jvx*sd)*dt;p.jvy+=(-p.jy*sk-p.jvy*sd)*dt;p.jx+=p.jvx*dt;p.jy+=p.jvy*dt;p.face=Math.max(0,p.face-dt)}
function collideCircle(p){const dx=puck.x-p.x,dy=puck.y-p.y,d=Math.hypot(dx,dy),min=p.r+puck.r;if(!(d<min&&d>0))return;const nx=dx/d,ny=dy/d,over=min-d,total=p.mass+puck.mass;puck.x+=nx*over*(p.mass/total);puck.y+=ny*over*(p.mass/total);const rvx=puck.vx-p.vx,rvy=puck.vy-p.vy,velN=rvx*nx+rvy*ny;if(velN<0){const restitution=.93,j=-(1+restitution)*velN/(1/puck.mass+1/p.mass),ix=j*nx,iy=j*ny;puck.vx+=ix/puck.mass;puck.vy+=iy/puck.mass;p.vx-=ix/p.mass*.18;p.vy-=iy/p.mass*.18;const tx=-ny,ty=nx,vt=rvx*tx+rvy*ty,fr=.055;puck.vx-=vt*tx*fr;puck.vy-=vt*ty*fr;const impact=Math.min(4,Math.abs(j)/550);p.jvx-=nx*(2.5+impact*2);p.jvy-=ny*(2.5+impact*2);p.face=.15;audio.hit(impact);spawn(puck.x,puck.y,p.color,5+Math.floor(impact*2))}}
function stepPhysics(dt){players.forEach(p=>stepMallet(p,dt));puck.x+=puck.vx*dt;puck.y+=puck.vy*dt;const goalH=Math.min(state.h*.35,190),gy=(state.h-goalH)/2,bounce=.965;if(puck.y-puck.r<0){puck.y=puck.r;puck.vy=Math.abs(puck.vy)*bounce;audio.wall()}if(puck.y+puck.r>state.h){puck.y=state.h-puck.r;puck.vy=-Math.abs(puck.vy)*bounce;audio.wall()}const inGoal=puck.y>gy&&puck.y<gy+goalH;if(puck.x-puck.r<0){if(inGoal)return scoreGoal(1);puck.x=puck.r;puck.vx=Math.abs(puck.vx)*bounce;audio.wall()}if(puck.x+puck.r>state.w){if(inGoal)return scoreGoal(0);puck.x=state.w-puck.r;puck.vx=-Math.abs(puck.vx)*bounce;audio.wall()}players.forEach(collideCircle);const drag=Math.pow(.9992,dt*120);puck.vx*=drag;puck.vy*=drag;const sp=Math.hypot(puck.vx,puck.vy);if(sp>puck.max){puck.vx*=puck.max/sp;puck.vy*=puck.max/sp}}
function update(dt){if(state.roundDelay>0){state.roundDelay-=dt;return}updateKeyboard(dt);state.acc=Math.min(MAX_ACC,state.acc+dt);while(state.acc>=FIXED_DT){stepPhysics(FIXED_DT);state.acc-=FIXED_DT}state.trails.push({x:puck.x,y:puck.y,life:.16});if(state.trails.length>16)state.trails.shift();for(const t of state.trails)t.life-=dt;state.trails=state.trails.filter(t=>t.life>0);for(const q of state.particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=180*dt;q.life-=dt}state.particles=state.particles.filter(q=>q.life>0);state.shake=Math.max(0,state.shake-dt*18);state.flash=Math.max(0,state.flash-dt*3)}
function scoreGoal(winner){if(state.roundDelay>0)return;state.score[winner]++;$('#s1').textContent=state.score[0];$('#s2').textContent=state.score[1];state.shake=1;state.flash=1;audio.goal();spawn(winner===0?state.w-20:20,puck.y,winner===0?'#4cc9ff':'#ff6fae',38);say('GOAL!');if(navigator.vibrate)navigator.vibrate(35);if(state.score[winner]>=state.goalToWin){state.paused=true;setTimeout(()=>{const name=winner===0?'BLUE':'PINK';$('#resultTitle').textContent=name+' WIN!';$('#resultScore').textContent=state.score[0]+' - '+state.score[1];$('#resultOverlay').classList.add('show')},650)}else{state.roundDelay=.75;setTimeout(()=>{if(state.running&&!state.paused){resetPositions();state.roundDelay=0}},760)}}
function drawField(){const w=state.w,h=state.h,gH=Math.min(h*.35,190),gy=(h-gH)/2;const grd=ctx.createLinearGradient(0,0,w,h);grd.addColorStop(0,'#17324e');grd.addColorStop(.5,'#20213f');grd.addColorStop(1,'#4c203d');ctx.fillStyle=grd;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.12;for(let x=20;x<w;x+=52)for(let y=22;y<h;y+=52){ctx.fillStyle=((x+y)/52)%2?'#fff':'#ffe46b';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.strokeStyle='rgba(255,255,255,.34)';ctx.lineWidth=4;ctx.setLineDash([12,14]);ctx.beginPath();ctx.moveTo(w/2,0);ctx.lineTo(w/2,h);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(w/2,h/2,Math.min(72,h*.16),0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#69d7ff';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(0,gy);ctx.lineTo(0,gy+gH);ctx.stroke();ctx.strokeStyle='#ff77b5';ctx.beginPath();ctx.moveTo(w,gy);ctx.lineTo(w,gy+gH);ctx.stroke();ctx.fillStyle='rgba(0,0,0,.28)';ctx.fillRect(0,gy,14,gH);ctx.fillRect(w-14,gy,14,gH)}
function drawPuck(){const g=ctx.createRadialGradient(puck.x-puck.r*.35,puck.y-puck.r*.4,2,puck.x,puck.y,puck.r);g.addColorStop(0,'#fff');g.addColorStop(.18,'#fff4a8');g.addColorStop(.52,'#ffd44d');g.addColorStop(1,'#f38b3e');ctx.shadowColor='rgba(255,212,77,.65)';ctx.shadowBlur=18;ctx.fillStyle=g;ctx.beginPath();ctx.arc(puck.x,puck.y,puck.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
function drawPlayer(p){const speed=Math.min(1.4,Math.hypot(p.vx,p.vy)/1100),angle=Math.atan2(p.vy,p.vx);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(angle);const directional=.12*speed,jx=p.jx,jy=p.jy,sx=Math.max(.68,1+directional+jx-jy*.35),sy=Math.max(.68,1-directional*.5+jy-jx*.35);ctx.scale(sx,sy);const g=ctx.createRadialGradient(-p.r*.28,-p.r*.35,p.r*.08,0,0,p.r);g.addColorStop(0,'#fff');g.addColorStop(.12,p.color);g.addColorStop(1,p.dark);ctx.shadowColor='rgba(0,0,0,.28)';ctx.shadowBlur=16;ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(0,0,p.r,p.r*.93,0,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.rotate(-angle);ctx.fillStyle='#17213a';const eyeY=-p.r*.1;ctx.beginPath();ctx.arc(-p.r*.22,eyeY,p.r*.065,0,Math.PI*2);ctx.arc(p.r*.22,eyeY,p.r*.065,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#17213a';ctx.lineWidth=Math.max(3,p.r*.07);ctx.lineCap='round';ctx.beginPath();if(p.face>0){ctx.moveTo(-p.r*.18,p.r*.18);ctx.lineTo(0,p.r*.3);ctx.lineTo(p.r*.18,p.r*.18)}else ctx.arc(0,p.r*.15,p.r*.22,.15*Math.PI,.85*Math.PI);ctx.stroke();ctx.restore()}
function draw(){ctx.save();if(state.shake){const m=state.shake*5;ctx.translate((Math.random()-.5)*m,(Math.random()-.5)*m)}drawField();for(const t of state.trails){ctx.globalAlpha=Math.max(0,t.life/.16)*.28;ctx.fillStyle='#ffe46b';ctx.beginPath();ctx.arc(t.x,t.y,puck.r*.72,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;drawPuck();players.forEach(drawPlayer);for(const q of state.particles){ctx.globalAlpha=Math.max(0,q.life/.7);ctx.fillStyle=q.color;ctx.beginPath();ctx.arc(q.x,q.y,q.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(state.flash){ctx.fillStyle=`rgba(255,255,255,${state.flash*.13})`;ctx.fillRect(0,0,state.w,state.h)}ctx.restore()}
function loop(now){if(!state.running)return;const dt=Math.min(.033,(now-state.last)/1000||.016);state.last=now;if(!state.paused)update(dt);draw();requestAnimationFrame(loop)}
function openOverlay(sel){audio.unlock();audio.click();$(sel).classList.add('show')}
$('#startBtn').onclick=startMatch;$('#howBtn').onclick=()=>openOverlay('#howOverlay');$('#settingsBtn').onclick=()=>openOverlay('#settingsOverlay');document.querySelectorAll('.close').forEach(b=>b.onclick=()=>{audio.click();b.closest('.overlay').classList.remove('show')});
$('#pauseBtn').onclick=()=>{state.paused=true;openOverlay('#pauseOverlay')};$('#resumeBtn').onclick=()=>{audio.click();state.paused=false;$('#pauseOverlay').classList.remove('show');state.last=performance.now()};$('#restartBtn').onclick=()=>{audio.click();restart()};$('#titleBtn').onclick=()=>{audio.click();endToTitle()};$('#againBtn').onclick=()=>{audio.click();restart()};$('#resultTitleBtn').onclick=()=>{audio.click();endToTitle()};
$('#bgmToggle').onclick=()=>{settings.bgm=!settings.bgm;if(settings.bgm){audio.unlock();audio.startBgm()}else audio.stopBgm();saveSettings()};$('#sfxToggle').onclick=()=>{settings.sfx=!settings.sfx;saveSettings();if(settings.sfx){audio.unlock();audio.click()}};
function pauseForInterruption(){if(state.running&&!state.paused){state.paused=true;$('#pauseOverlay').classList.add('show')}}
window.addEventListener('keydown',e=>{const gameKeys=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyP','Escape'];if(gameKeys.includes(e.code))e.preventDefault();if(e.code==='KeyP'||e.code==='Escape'){if(state.running){if(state.paused&&$('#pauseOverlay').classList.contains('show'))$('#resumeBtn').click();else if(!state.paused)$('#pauseBtn').click()}return}keys.add(e.code);audio.resume()},{passive:false});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();pauseForInterruption()});window.addEventListener('pageshow',()=>{resize();audio.resume()});window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);window.addEventListener('orientationchange',()=>setTimeout(resize,120));document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();pauseForInterruption()}else audio.resume()});document.addEventListener('contextmenu',e=>{if(state.running)e.preventDefault()});document.addEventListener('dragstart',e=>e.preventDefault());
syncToggles();resize();
})();
